version: "3.7"
services:
  mysql:
    image: mysql:8
    container_name: mysql_jaw
    volumes:
      - ./docker/data/db:/var/lib/mysql
      - ./dumps:/var/www/html
    command: "--default-authentication-plugin=mysql_native_password"
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME:-jaw}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
      - DOCKER_USER_UID=${UID}
      - DOCKER_USER_GID=${GID}

  nginx:
    container_name: nginx_jaw
    build:
      context: nginx
    ports:
      - ${PORT_HTTP:-80}:80
    environment:
      PHP_FPM_UPSTREAM: php:9000
      DNS_RESOLVER: 127.0.0.11
    volumes:
      - ./../../public:/var/www/html/public:ro

  php:
    user: "${UID}:${GID}"
    hostname: php_jaw
    container_name: php-jaw
    build:
      context: php
      args:
        GITHUB_SECRET_TOKEN: ${GITHUB_SECRET_TOKEN}
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      DEBUG_LEVEL: debug
    dns: 8.8.8.8
    volumes:
      - ./../..:/var/www/html
