version: '2.1'
executors:
  php:
    docker:
      - image: php:8.1-alpine
    working_directory: ~/repo

commands:
  alpine_checkout:
    description: Optimize Alpine checkout.
    steps:
      - run:
          name: "Install requirements for checkout"
          command: |
            apk add --update git openssh-client curl make
      - checkout

jobs:
  composer:
    executor: php
    steps:
      - alpine_checkout
      - restore_cache:
          key: composer-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
      - run:
          name: composer
          command: |
            if [[ ! -f vendor/autoload.php ]]; then
                curl https://getcomposer.org/composer-stable.phar --location --silent  --output /usr/bin/composer; \
                chmod +x /usr/bin/composer; \
                composer install --no-progress --no-interaction;
            fi \

      - save_cache:
          key: composer-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
          paths:
            - ./vendor
      - persist_to_workspace:
          root: .
          paths:
            - vendor

  phpcs:
    executor: php
    steps:
      - alpine_checkout
      - attach_workspace:
          at: .
      - run:
          name: phpcs
          command: |
            cd tools/php-cs-fixer; \
            curl https://getcomposer.org/composer-stable.phar --location --silent  --output /usr/bin/composer; \
            chmod +x /usr/bin/composer; \
            composer install --no-progress --no-interaction; \
            cd .. \
            vendor/bin/php-cs-fixer fix src --dry-run;

  phpstan:
    executor: php
    steps:
      - alpine_checkout
      - attach_workspace:
          at: .
      - run:
          name: phpstan
          command: make phpstan

  phpunit:
    executor: php
    steps:
      - alpine_checkout
      - attach_workspace:
          at: .
      - run:
          name: phpunit
          command: make phpunit

workflows:
  version: '2'
  Code quality:
    jobs:
      - composer
      - phpcs:
          requires:
            - composer
      - phpstan:
          requires:
            - composer
      - phpunit:
          requires:
            - composer
