version: "3.7"
services:
  mysql:
    image: mysql:8
    container_name: mysql_jaw
    volumes:
      - ./docker/data/db:/var/lib/mysql
    command: "--default-authentication-plugin=mysql_native_password"
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME:-jaw}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
